# Generated by Django 4.2.2 on 2023-07-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping_address',
        ),
    ]
